CREATE TABLE mxd_items(
`id`   int   PRIMARY KEY   NOT NULL      AUTO_INCREMENT    COMMENT '自增ID',
`type_id`   int  COMMENT '类型id',
`name`   varchar(20)      NOT NULL         COMMENT '物品名',
`category_id`   int      NOT NULL         COMMENT '菜单id',
`status`   tinyint      NOT NULL   DEFAULT 0       COMMENT '状态',
`deleted`   tinyint      NOT NULL   DEFAULT 0       COMMENT '是否删除',
`server_area`   varchar(20)      NOT NULL   DEFAULT ''       COMMENT '区服',
`career`   varchar(20)      NOT NULL   DEFAULT ''       COMMENT '可装备职业',
`req_lv`   int      NOT NULL          COMMENT '装备等级',
`price`   decimal(20,2)     NOT NULL        COMMENT '价格',
`star_force`   int      NOT NULL   DEFAULT 0       COMMENT '星力',
`att_str`   int      NOT NULL   DEFAULT 0       COMMENT '力量',
`att_dex`   int      NOT NULL   DEFAULT 0       COMMENT '敏捷',
`att_int`   int      NOT NULL   DEFAULT 0       COMMENT '智力',
`att_luk`   int      NOT NULL   DEFAULT 0       COMMENT '幸运',
`potential_color`   int      NOT NULL   DEFAULT 0       COMMENT '潜能颜色',
`potential_quality`   int      NOT NULL   DEFAULT 0       COMMENT '潜能属性',
`add_potential_color`   int      NOT NULL   DEFAULT 0       COMMENT '附加潜能颜色',
`add_potential_quality`   int      NOT NULL   DEFAULT 0       COMMENT '附加潜能属性',
`hammer`   int      NOT NULL   DEFAULT 0       COMMENT '锤子',
`create_time`   datetime      NOT NULL   DEFAULT CURRENT_TIMESTAMP       COMMENT '创建时间',
`update_time`   datetime      NOT NULL   DEFAULT CURRENT_TIMESTAMP   ON UPDATE CURRENT_TIMESTAMP    COMMENT '修改时间',
`create_user_id`   int  COMMENT '创建用户id',
`create_user_name`   varchar(20)      NOT NULL   DEFAULT ''       COMMENT '创建用户',
`update_user_id`   int    COMMENT  '更新用户id',
`update_user_name`   varchar(20)         DEFAULT ''       COMMENT '更新用户名'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT="物品表";